# Generated by Django 5.0.1 on 2024-02-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostilas', '0003_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='apostila',
            name='tags',
            field=models.ManyToManyField(to='apostilas.tags'),
        ),
    ]
